# Matrix Library

cc_test(
  name = "zmatrix_test",
  size = "small",
  srcs = ["zmatrix_test.cpp"],
  deps = [
      "@googletest//:gtest_main",
      ":zmatrix",
      ],
)

cc_library(
    name = "zmatrix",
    srcs = ["zmatrix.cpp"],
    hdrs = ["zmatrix.hpp"],
)